//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyAngile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhanvien
    {
        public string Masanpham { get; set; }
        public string tensanpham { get; set; }
        public string danhmuc { get; set; }
        public Nullable<double> giasanpham { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<System.DateTime> ngaythem { get; set; }
    }
}
